import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";
import QueryProvider from "@/components/providers/QueryProvider";
import AuthProvider from "@/components/providers/AuthProvider";

import Footer from '../components/Footer'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
    //     <head>
    //         <link
    //            rel="stylesheet"
    //            href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css"
    //            integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI="
    //            crossOrigin=""
    //         />
    //      </head>
    //   <body
    //     className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    //   >
    //                 <Navigation />

    //     {children}
    //     <Footer />
    //   </body>
    // </html>
    <html lang="en">
    <head>
       <link
          rel="stylesheet"
          href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css"
          integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI="
          crossOrigin=""
       />
    </head>
    <body
       className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
       <QueryProvider>
          <AuthProvider>
             <Navigation />
             {children}
             <Footer />
          </AuthProvider>
       </QueryProvider>
    </body>
 </html>
  );
}
